### ISSUE TITLE
LICENSE ?

### ISSUE THREAD

**Issue by nschimme** [jamesheston/react-redux-mud-client#2]
What is the license of this repository?

**Comment by jamesheston** [comment]
Do whatever you want with it. As long as it can be of any use to anyone
else, I don't care. Thanks for the interest!

**Comment by nschimme** [comment]
Sounds like you prefer a permissive MIT license then ;-)

**Comment by jamesheston** [comment]
added MIT license

**Comment by nschimme** [comment]
Thanks, but you didn't add your name :-P

Edit it to say `James Heston` and `Copyright 2017`?

**Comment by jamesheston** [comment]
Just saw this in my email. Updated the copyright.

**Comment by nschimme** [comment]
Great!
